name: ticketing-actions

on:
  push:
    branches:
      - main
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TICKETING_USERNAME }}
          aws-secret-access-key: ${{ secrets.TICKETING_PASSWORD }}
          aws-region: ap-northeast-2

      - name: Deploy to ASG
        run: | 
          ASG_NAME= "ticketing-auto-scaling"

          NEW_AMI= "ticketing-ami"

          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --launch-configuration-name $NEW_AMI
          
